export type MenuTag = 'veg' | 'non-veg' | 'egg' | 'spicy' | 'signature';

export interface MenuItem {
  id: string;
  name: string;
  price: number | string;
  priceNote?: string;
  category: string;
  subCategory?: string;
  tags: MenuTag[];
  description?: string;
  image?: string;
  isSignature?: boolean;
}

export interface MenuCategory {
  id: string;
  name: string;
  icon: string;
  description: string;
  items: MenuItem[];
}

// ─── Unsplash images by cuisine type ──────────────────────────────────────────
const IMG = {
  biryani: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=600&q=80',
  chickenMandi: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80',
  chickenGravy: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=600&q=80',
  muttonGravy: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=600&q=80',
  tandoori: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&q=80',
  vegStarter: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80',
  soup: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
  friedRice: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80',
  noodles: 'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80',
  naan: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
  seafood: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=600&q=80',
  dessert: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=600&q=80',
  beverage: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
  paneer: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80',
  kebab: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&q=80',
  egg: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=600&q=80',
};

export const menuData: MenuCategory[] = [
  // ─────────────────────── SIGNATURE MANDI ─────────────────────────────────
  {
    id: 'mandi',
    name: 'Signature Mandi',
    icon: '🍖',
    description: 'Our signature slow-cooked mandi — tender meat over fragrant basmati, the pride of Arabian cuisine',
    items: [
      { id: 'm1',  name: 'Chicken Mandi 1PC',         price: 249,  tags: ['non-veg'],              image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Mandi' },
      { id: 'm2',  name: 'Chicken Mandi 2PC',         price: 450,  tags: ['non-veg'],              image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Mandi' },
      { id: 'm3',  name: 'Chicken Mandi 3PC',         price: 700,  tags: ['non-veg'],              image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Mandi' },
      { id: 'm4',  name: 'Chicken Mandi 4PC',         price: 850,  tags: ['non-veg', 'signature'], image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Mandi', isSignature: true },
      { id: 'm5',  name: 'Chicken Juicy 1PC',         price: 280,  tags: ['non-veg'],              image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Juicy' },
      { id: 'm6',  name: 'Chicken Juicy 2PC',         price: 499,  tags: ['non-veg'],              image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Juicy' },
      { id: 'm7',  name: 'Chicken Juicy 3PC',         price: 700,  tags: ['non-veg'],              image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Juicy' },
      { id: 'm8',  name: 'Chicken Juicy 4PC',         price: 850,  tags: ['non-veg'],              image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Juicy' },
      { id: 'm9',  name: 'Chicken Al Faham (Half 2P)', price: 560, tags: ['non-veg', 'signature'], image: IMG.tandoori,     category: 'mandi', subCategory: 'Chicken Al Faham', isSignature: true },
      { id: 'm10', name: 'Chicken Al Faham (Full 4PC)', price: 1000, tags: ['non-veg', 'signature'], image: IMG.tandoori,  category: 'mandi', subCategory: 'Chicken Al Faham', isSignature: true },
      { id: 'm11', name: 'Chicken Broasted 1PC',       price: 300,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Broasted' },
      { id: 'm12', name: 'Chicken Broasted 2PC',       price: 500,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Broasted' },
      { id: 'm13', name: 'Chicken Broasted 3PC',       price: 700,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Broasted' },
      { id: 'm14', name: 'Chicken Broasted 4PC',       price: 900,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Broasted' },
      { id: 'm15', name: 'Chicken Ghee Roast 1PC',     price: 300,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Ghee Roast' },
      { id: 'm16', name: 'Chicken Ghee Roast 2PC',     price: 500,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Ghee Roast' },
      { id: 'm17', name: 'Chicken Ghee Roast 3PC',     price: 750,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Ghee Roast' },
      { id: 'm18', name: 'Chicken Ghee Roast 4PC',     price: 900,  tags: ['non-veg'],             image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Ghee Roast' },
      { id: 'm19', name: 'Tandoori Chicken Mandi 1PC', price: 320,  tags: ['non-veg', 'signature'], image: IMG.tandoori,  category: 'mandi', subCategory: 'Tandoori Chicken Mandi' },
      { id: 'm20', name: 'Tandoori Chicken Mandi 2PC', price: 560,  tags: ['non-veg', 'signature'], image: IMG.tandoori,  category: 'mandi', subCategory: 'Tandoori Chicken Mandi' },
      { id: 'm21', name: 'Tandoori Chicken Mandi 3PC', price: 700,  tags: ['non-veg', 'signature'], image: IMG.tandoori,  category: 'mandi', subCategory: 'Tandoori Chicken Mandi' },
      { id: 'm22', name: 'Tandoori Chicken Mandi 4PC', price: 1000, tags: ['non-veg', 'signature'], image: IMG.tandoori,  category: 'mandi', subCategory: 'Tandoori Chicken Mandi', isSignature: true },
      { id: 'm23', name: 'Mutton Mandi 1PC',           price: 300,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Mandi' },
      { id: 'm24', name: 'Mutton Mandi 2PC',           price: 550,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Mandi' },
      { id: 'm25', name: 'Mutton Mandi 3PC',           price: 800,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Mandi' },
      { id: 'm26', name: 'Mutton Mandi 4PC',           price: 950,  tags: ['non-veg', 'signature'], image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Mandi', isSignature: true },
      { id: 'm27', name: 'Mutton Juicy 1PC',           price: 340,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Juicy' },
      { id: 'm28', name: 'Mutton Juicy 2PC',           price: 550,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Juicy' },
      { id: 'm29', name: 'Mutton Juicy 3PC',           price: 850,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Juicy' },
      { id: 'm30', name: 'Mutton Juicy 4PC',           price: 980,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Juicy' },
      { id: 'm31', name: 'Mutton Ghee Roast 1PC',      price: 350,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Ghee Roast' },
      { id: 'm32', name: 'Mutton Ghee Roast 2PC',      price: 580,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Ghee Roast' },
      { id: 'm33', name: 'Mutton Ghee Roast 3PC',      price: 850,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Ghee Roast' },
      { id: 'm34', name: 'Mutton Ghee Roast 4PC',      price: 980,  tags: ['non-veg'],             image: IMG.muttonGravy, category: 'mandi', subCategory: 'Mutton Ghee Roast' },
      { id: 'm35', name: 'Fish Mandi 1PC',             price: 350,  tags: ['non-veg'],             image: IMG.seafood,     category: 'mandi', subCategory: 'Fish Mandi' },
      { id: 'm36', name: 'Fish Mandi 2PC',             price: 550,  tags: ['non-veg'],             image: IMG.seafood,     category: 'mandi', subCategory: 'Fish Mandi' },
      { id: 'm37', name: 'Fish Mandi 3PC',             price: 820,  tags: ['non-veg'],             image: IMG.seafood,     category: 'mandi', subCategory: 'Fish Mandi' },
      { id: 'm38', name: 'Fish Mandi 4PC',             price: 980,  tags: ['non-veg'],             image: IMG.seafood,     category: 'mandi', subCategory: 'Fish Mandi' },
      { id: 'm39', name: 'Paneer Tikka Mandi 1PC',     price: 270,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm40', name: 'Paneer Tikka Mandi 2PC',     price: 450,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm41', name: 'Paneer Tikka Mandi 3PC',     price: 650,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm42', name: 'Paneer Tikka Mandi 4PC',     price: 850,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm43', name: 'Paneer Mandi 1PC',           price: 270,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm44', name: 'Paneer Mandi 2PC',           price: 450,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm45', name: 'Paneer Mandi 3PC',           price: 650,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm46', name: 'Paneer Mandi 4PC',           price: 850,  tags: ['veg'],                 image: IMG.paneer,      category: 'mandi', subCategory: 'Paneer Mandi' },
      { id: 'm47', name: 'TMS SPL Mix Mandi (Mixed Platter)', price: 1499, tags: ['non-veg', 'signature'], image: IMG.chickenMandi, category: 'mandi', subCategory: 'Special', isSignature: true, description: 'Chicken Fry + Mutton Fry + Juicy Chicken + Brosted Chicken (1PC each)' },
      { id: 'm48', name: 'Chicken 65 Mandi 1 Person',  price: 279,  tags: ['non-veg', 'spicy'],    image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
      { id: 'm49', name: 'Chicken 65 Mandi 2 Person',  price: 490,  tags: ['non-veg', 'spicy'],    image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
      { id: 'm50', name: 'Chicken 65 Mandi 4 Person',  price: 880,  tags: ['non-veg', 'spicy'],    image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
      { id: 'm51', name: 'Chicken Dragon Mandi 1 Person', price: 299, tags: ['non-veg', 'spicy'], image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
      { id: 'm52', name: 'Chicken Dragon Mandi 2 Person', price: 520, tags: ['non-veg', 'spicy'], image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
      { id: 'm53', name: 'Chicken Dragon Mandi 4 Person', price: 890, tags: ['non-veg', 'spicy'], image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
      { id: 'm54', name: 'Chicken Lollypop Mandi 1 Person', price: 280, tags: ['non-veg'],        image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
      { id: 'm55', name: 'Chicken Lollypop Mandi 4 Person', price: 890, tags: ['non-veg'],        image: IMG.chickenMandi, category: 'mandi', subCategory: 'Chicken Starter Mandi' },
    ],
  },

  // ─────────────────────── SOUPS, SALADS & RAITHA ──────────────────────────
  {
    id: 'soups',
    name: 'Soups, Salads & Raitha',
    icon: '🥣',
    description: 'Warm beginnings and fresh accompaniments crafted to perfection',
    items: [
      { id: 's1',  name: 'Sweetcorn Veg Soup',        price: 120, tags: ['veg'],     image: IMG.soup,     category: 'soups' },
      { id: 's2',  name: 'Sweetcorn Chicken Soup',    price: 150, tags: ['non-veg'], image: IMG.soup,     category: 'soups' },
      { id: 's3',  name: 'Hot & Sour Veg Soup',       price: 120, tags: ['veg', 'spicy'], image: IMG.soup, category: 'soups' },
      { id: 's4',  name: 'Hot & Sour Chicken Soup',   price: 150, tags: ['non-veg', 'spicy'], image: IMG.soup, category: 'soups' },
      { id: 's5',  name: 'Mushroom Soup',              price: 120, tags: ['veg'],     image: IMG.soup,     category: 'soups' },
      { id: 's6',  name: 'Chicken Mencho Soup',        price: 160, tags: ['non-veg'], image: IMG.soup,     category: 'soups' },
      { id: 's7',  name: 'Veg Mencho Soup',            price: 140, tags: ['veg'],     image: IMG.soup,     category: 'soups' },
      { id: 's8',  name: 'Mutton Soup',                price: 199, tags: ['non-veg'], image: IMG.soup,     category: 'soups' },
      { id: 's9',  name: 'Garden Salad',               price: 49,  tags: ['veg'],     image: IMG.vegStarter, category: 'soups' },
      { id: 's10', name: 'Cucumber Salad',             price: 30,  tags: ['veg'],     image: IMG.vegStarter, category: 'soups' },
      { id: 's11', name: 'Mixed Raitha',               price: 30,  tags: ['veg'],     image: IMG.vegStarter, category: 'soups' },
      { id: 's12', name: 'Boondi Raitha',              price: 50,  tags: ['veg'],     image: IMG.vegStarter, category: 'soups' },
    ],
  },

  // ─────────────────────── VEG STARTERS ────────────────────────────────────
  {
    id: 'veg-starters',
    name: 'Veg Starters',
    icon: '🥦',
    description: 'Crispy, flavourful vegetarian starters to ignite your appetite',
    items: [
      { id: 'vs1',  name: 'Paneer Pakoda',          price: 180, tags: ['veg'],           image: IMG.paneer,     category: 'veg-starters' },
      { id: 'vs2',  name: 'Paneer Manchurian',      price: 180, tags: ['veg'],           image: IMG.paneer,     category: 'veg-starters' },
      { id: 'vs3',  name: 'Paneer Chilli',          price: 180, tags: ['veg', 'spicy'],  image: IMG.paneer,     category: 'veg-starters' },
      { id: 'vs4',  name: 'Paneer Majestic',        price: 199, tags: ['veg', 'signature'], image: IMG.paneer,  category: 'veg-starters', isSignature: true },
      { id: 'vs5',  name: 'Mushroom Manchurian',    price: 180, tags: ['veg'],           image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs6',  name: 'Mushroom Chilli',        price: 180, tags: ['veg', 'spicy'],  image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs7',  name: 'Mushroom 65',            price: 180, tags: ['veg', 'spicy'],  image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs8',  name: 'Babycorn Manchurian',    price: 149, tags: ['veg'],           image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs9',  name: 'Babycorn Chilli',        price: 149, tags: ['veg', 'spicy'],  image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs10', name: 'Gobi Manchurian',        price: 120, tags: ['veg'],           image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs11', name: 'Gobi Chilli',            price: 120, tags: ['veg', 'spicy'],  image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs12', name: 'Gobi 65',                price: 120, tags: ['veg', 'spicy'],  image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs13', name: 'Aloo 65',                price: 120, tags: ['veg'],           image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs14', name: 'Vegetable Bullet',       price: 120, tags: ['veg'],           image: IMG.vegStarter, category: 'veg-starters' },
      { id: 'vs15', name: 'Crispycorn',             price: 180, tags: ['veg'],           image: IMG.vegStarter, category: 'veg-starters' },
      // Tandoori Veg
      { id: 'vs16', name: 'Hariyali Paneer Tikka',  price: 199, tags: ['veg', 'signature'], image: IMG.tandoori, category: 'veg-starters', isSignature: true },
      { id: 'vs17', name: 'Paneer Tikka',           price: 199, tags: ['veg'],           image: IMG.tandoori,   category: 'veg-starters' },
      { id: 'vs18', name: 'Aloo Chatpata Kabab',    price: 180, tags: ['veg'],           image: IMG.tandoori,   category: 'veg-starters' },
      { id: 'vs19', name: 'Mushroom Cheese Kabab',  price: 199, tags: ['veg'],           image: IMG.tandoori,   category: 'veg-starters' },
    ],
  },

  // ─────────────────────── NON-VEG STARTERS ────────────────────────────────
  {
    id: 'nonveg-starters',
    name: 'Non-Veg Starters',
    icon: '🍗',
    description: 'Bold, smoky and spiced — our non-veg starters are impossible to resist',
    items: [
      { id: 'nv1',  name: 'Chicken Fry Oil Kabab',           price: 199, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv2',  name: 'Chilli Chicken',                  price: 199, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv3',  name: 'Chicken Lollypop (4PCS)',         price: 199, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv4',  name: 'Chicken 65',                      price: 199, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv5',  name: 'Chicken Black Pepper Leg Piece (4PCS)', price: 249, tags: ['non-veg', 'spicy'], image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv6',  name: 'Chicken Black Pepper',            price: 199, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv7',  name: 'Ginger Chicken',                  price: 199, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv8',  name: 'Schezwan Chicken Boneless',       price: 199, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv9',  name: 'Chicken Majestic Boneless',       price: 199, tags: ['non-veg', 'signature'], image: IMG.chickenGravy, category: 'nonveg-starters', isSignature: true },
      { id: 'nv10', name: 'Lemon Chicken Boneless',          price: 199, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv11', name: 'Garlic Chicken Boneless',         price: 199, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv12', name: 'Chicken Ghee Roast',              price: 199, tags: ['non-veg', 'signature'], image: IMG.chickenGravy, category: 'nonveg-starters', isSignature: true },
      { id: 'nv13', name: 'Telangana Chicken Wings',         price: 199, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv14', name: 'Guntur Chicken (with bone)',      price: 199, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv15', name: 'Andhra Chilli Chicken (with bone)', price: 199, tags: ['non-veg', 'spicy'], image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv16', name: 'Chicken 555',                     price: 199, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv17', name: 'Cashewnut Chicken',               price: 249, tags: ['non-veg', 'signature'], image: IMG.chickenGravy, category: 'nonveg-starters', isSignature: true },
      { id: 'nv18', name: 'Chicken Manchurian',              price: 199, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv19', name: 'Dragon Chicken',                  price: 200, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'nonveg-starters' },
      { id: 'nv20', name: 'Chicken Kaati Roll',              price: 149, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'nonveg-starters' },
      // Mutton starters
      { id: 'nv21', name: 'Mutton Pepper Fry',               price: 299, tags: ['non-veg', 'spicy'],   image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv22', name: 'Mysore Mutton',                   price: 299, tags: ['non-veg', 'spicy'],   image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv23', name: 'Tawa Mutton',                     price: 299, tags: ['non-veg'],             image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv24', name: 'Mutton Roasted',                  price: 299, tags: ['non-veg'],             image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv25', name: 'Garlic Mutton',                   price: 299, tags: ['non-veg'],             image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv26', name: 'Mutton Chilli',                   price: 299, tags: ['non-veg', 'spicy'],   image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv27', name: 'Mutton Keema',                    price: 299, tags: ['non-veg'],             image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv28', name: 'Mutton Rogan Josh',               price: 299, tags: ['non-veg', 'signature'], image: IMG.muttonGravy, category: 'nonveg-starters', subCategory: 'Mutton Starters', isSignature: true },
      { id: 'nv29', name: 'Mutton Saag',                     price: 299, tags: ['non-veg'],             image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      { id: 'nv30', name: 'Mutton Masala',                   price: 299, tags: ['non-veg', 'spicy'],   image: IMG.muttonGravy,  category: 'nonveg-starters', subCategory: 'Mutton Starters' },
      // Tandoori Non-Veg
      { id: 'nv31', name: 'TMS Special Tandoori Wings',      price: 249, tags: ['non-veg', 'signature'], image: IMG.tandoori,   category: 'nonveg-starters', subCategory: 'Tandoori', isSignature: true },
      { id: 'nv32', name: 'Tandoori Chicken Kabab (Full)',   price: 499, tags: ['non-veg', 'signature'], image: IMG.tandoori,   category: 'nonveg-starters', subCategory: 'Tandoori', isSignature: true },
      { id: 'nv33', name: 'Tandoori Chicken Kabab (Half)',   price: 299, tags: ['non-veg'],             image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Tandoori' },
      { id: 'nv34', name: 'Hariyali Chicken Kabab (6PCS)',   price: 249, tags: ['non-veg'],             image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Tandoori' },
      { id: 'nv35', name: 'Chicken Tikka (6PCS)',            price: 249, tags: ['non-veg'],             image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Tandoori' },
      { id: 'nv36', name: 'Chicken Malai Tikka (6PCS)',      price: 249, tags: ['non-veg', 'signature'], image: IMG.tandoori,   category: 'nonveg-starters', subCategory: 'Tandoori', isSignature: true },
      { id: 'nv37', name: 'Chicken Tangidi Kabab (4PCS)',    price: 249, tags: ['non-veg'],             image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Tandoori' },
      { id: 'nv38', name: 'Fish Tikka (6PCS)',               price: 249, tags: ['non-veg'],             image: IMG.seafood,     category: 'nonveg-starters', subCategory: 'Tandoori' },
      { id: 'nv39', name: 'Mutton Sheek Kabab',              price: 299, tags: ['non-veg'],             image: IMG.kebab,       category: 'nonveg-starters', subCategory: 'Tandoori' },
      { id: 'nv40', name: 'Peri Peri Chicken Kabab (6PCS)', price: 249, tags: ['non-veg', 'spicy'],    image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Tandoori' },
      // Grill
      { id: 'nv41', name: 'Grill Chicken (Full)',            price: 499, tags: ['non-veg', 'signature'], image: IMG.tandoori,   category: 'nonveg-starters', subCategory: 'Grill', isSignature: true },
      { id: 'nv42', name: 'Grill Chicken (Half)',            price: 299, tags: ['non-veg'],             image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Grill' },
      { id: 'nv43', name: 'Al Faham (Full)',                 price: 499, tags: ['non-veg', 'signature'], image: IMG.tandoori,   category: 'nonveg-starters', subCategory: 'Grill', isSignature: true },
      { id: 'nv44', name: 'Al Faham (Half)',                 price: 299, tags: ['non-veg'],             image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Grill' },
      { id: 'nv45', name: 'Grill Pepper Fry (Full)',         price: 499, tags: ['non-veg', 'spicy'],   image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Grill' },
      { id: 'nv46', name: 'Grill Spicy Chicken (Full)',      price: 499, tags: ['non-veg', 'spicy'],   image: IMG.tandoori,    category: 'nonveg-starters', subCategory: 'Grill' },
      { id: 'nv47', name: 'SPL Platter', price: 899, tags: ['non-veg', 'signature'], image: IMG.tandoori, category: 'nonveg-starters', subCategory: 'Grill', isSignature: true, description: 'Chicken Tikka, Tandoori Chicken, Malai Kabab, Sheek Kabab, Fish Tikka, Tangidi Kabab (2PCS each)' },
      // Egg
      { id: 'nv48', name: 'Egg Manchurian',                  price: 149, tags: ['egg'],               image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv49', name: 'Egg Pakoda',                      price: 149, tags: ['egg'],               image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv50', name: 'Egg Masala',                      price: 149, tags: ['egg'],               image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv51', name: 'Egg 65',                          price: 149, tags: ['egg', 'spicy'],      image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv52', name: 'Egg Chilli',                      price: 149, tags: ['egg', 'spicy'],      image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv53', name: 'Egg Roasted (4PCS)',              price: 80,  tags: ['egg'],               image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv54', name: 'Egg Omlette',                     price: 60,  tags: ['egg'],               image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv55', name: 'Egg Bhurjji',                     price: 99,  tags: ['egg'],               image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
      { id: 'nv56', name: 'Egg Kaati Roll',                  price: 80,  tags: ['egg'],               image: IMG.egg,          category: 'nonveg-starters', subCategory: 'Egg Items' },
    ],
  },

  // ─────────────────────── BIRYANI ─────────────────────────────────────────
  {
    id: 'biryani',
    name: 'Biryani',
    icon: '🍚',
    description: 'Slow-cooked Hyderabadi dum biryani — every grain tells a story of centuries of Nizami cuisine',
    items: [
      { id: 'b1',  name: 'Hyderabadi Chicken Dum Biryani', price: 149, priceNote: 'Single | Full ₹240 | Family ₹599 | Jumbo ₹799', tags: ['non-veg', 'signature'], image: IMG.biryani, category: 'biryani', isSignature: true },
      { id: 'b2',  name: 'Hyderabadi Mutton Dum Biryani', price: 249, priceNote: 'Single | Full ₹349 | Family ₹799 | Jumbo ₹1050', tags: ['non-veg', 'signature'], image: IMG.biryani, category: 'biryani', isSignature: true },
      { id: 'b3',  name: 'SPL Chicken Dum Biryani (Boneless)', price: 199, priceNote: 'Single | Full ₹299 | Family ₹699 | Jumbo ₹899', tags: ['non-veg', 'signature'], image: IMG.biryani, category: 'biryani', isSignature: true },
      { id: 'b4',  name: 'Chicken Lollypop Biryani',      price: 229, priceNote: 'Single | Full ₹369 | Family ₹799 | Jumbo ₹999', tags: ['non-veg'],    image: IMG.biryani, category: 'biryani' },
      { id: 'b5',  name: 'Fry Piece Biryani',             price: 169, priceNote: 'Single | Full ₹299 | Family ₹750 | Jumbo ₹950', tags: ['non-veg'],    image: IMG.biryani, category: 'biryani' },
      { id: 'b6',  name: 'Egg Dum Biryani',               price: 120, priceNote: 'Single | Full ₹240 | Family ₹450 | Jumbo ₹650', tags: ['egg'],        image: IMG.biryani, category: 'biryani' },
      { id: 'b7',  name: 'Veg Biryani',                   price: 120, priceNote: 'Single | Full ₹240 | Family ₹450 | Jumbo ₹650', tags: ['veg'],        image: IMG.biryani, category: 'biryani' },
      { id: 'b8',  name: 'Paneer Biryani',                price: 159, priceNote: 'Single | Full ₹299 | Family ₹750 | Jumbo ₹950', tags: ['veg'],        image: IMG.biryani, category: 'biryani' },
      { id: 'b9',  name: 'Mushroom Biryani',              price: 159, priceNote: 'Single | Full ₹299 | Family ₹750 | Jumbo ₹950', tags: ['veg'],        image: IMG.biryani, category: 'biryani' },
      { id: 'b10', name: 'Soya Keema Biryani',            price: 149, priceNote: 'Single | Full ₹249 | Family ₹649 | Jumbo ₹900', tags: ['veg'],        image: IMG.biryani, category: 'biryani' },
      { id: 'b11', name: 'Aloo Dum Biryani',              price: 130, priceNote: 'Single | Full ₹229 | Family ₹449 | Jumbo ₹649', tags: ['veg'],        image: IMG.biryani, category: 'biryani' },
      { id: 'b12', name: 'Mughlai Biryani',               price: 249, priceNote: 'Single | Full ₹349 | Family ₹599 | Jumbo ₹799', tags: ['non-veg', 'signature'], image: IMG.biryani, category: 'biryani', isSignature: true },
      { id: 'b13', name: 'Fish Biryani',                  price: 229, priceNote: 'Single | Full ₹349 | Family ₹799 | Jumbo ₹999', tags: ['non-veg'],    image: IMG.biryani, category: 'biryani' },
      { id: 'b14', name: 'Prawns Biryani',                price: 249, priceNote: 'Single | Full ₹369 | Family ₹799 | Jumbo ₹1050', tags: ['non-veg'],   image: IMG.biryani, category: 'biryani' },
      { id: 'b15', name: 'Mutton Keema Biryani',          price: 399, priceNote: 'Single | Full ₹699 | Family ₹999 | Jumbo ₹1299', tags: ['non-veg', 'signature'], image: IMG.biryani, category: 'biryani', isSignature: true },
      { id: 'b16', name: 'Chicken Keema Biryani',         price: 299, priceNote: 'Single | Full ₹499 | Family ₹699 | Jumbo ₹999', tags: ['non-veg'],    image: IMG.biryani, category: 'biryani' },
      { id: 'b17', name: 'Kaju Biryani',                  price: 220, priceNote: 'Single | Full ₹430 | Family ₹799 | Jumbo ₹1050', tags: ['veg'],       image: IMG.biryani, category: 'biryani' },
    ],
  },

  // ─────────────────────── GRAVIES ─────────────────────────────────────────
  {
    id: 'gravies',
    name: 'Main Course Gravies',
    icon: '🍛',
    description: 'Rich, aromatic curries slow-simmered with hand-ground spices — the heart of Indian cuisine',
    items: [
      // Non-Veg
      { id: 'g1',  name: 'Butter Chicken',           price: 249, tags: ['non-veg', 'signature'], image: IMG.chickenGravy, category: 'gravies', isSignature: true },
      { id: 'g2',  name: 'Chicken Tikka Masala',     price: 249, tags: ['non-veg', 'signature'], image: IMG.chickenGravy, category: 'gravies', isSignature: true },
      { id: 'g3',  name: 'Kadai Chicken',            price: 249, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g4',  name: 'Methi Chicken',            price: 249, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g5',  name: 'Chicken Curry',            price: 249, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g6',  name: 'Chicken Saag',             price: 249, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g7',  name: 'Chicken Do Pyaza',         price: 249, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g8',  name: 'Chicken Kolhapuri',        price: 249, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g9',  name: 'Chicken Fry',              price: 249, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g10', name: 'Chicken Masala',           price: 249, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g11', name: 'Palak Chicken',            price: 249, tags: ['non-veg'],             image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g12', name: 'Mughalai Chicken',         price: 249, tags: ['non-veg', 'signature'], image: IMG.chickenGravy, category: 'gravies', isSignature: true },
      { id: 'g13', name: 'Chicken Kali Mirchi',      price: 249, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'gravies' },
      { id: 'g14', name: 'Pepper Chicken Gravy',     price: 249, tags: ['non-veg', 'spicy'],    image: IMG.chickenGravy, category: 'gravies' },
      // Veg gravies
      { id: 'g15', name: 'Veg Kolhapuri',            price: 149, tags: ['veg', 'spicy'],        image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g16', name: 'Kaju Tomato Masala',       price: 199, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g17', name: 'Kadai Vegetable',          price: 149, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g18', name: 'Paneer Butter Masala',     price: 199, tags: ['veg', 'signature'],    image: IMG.paneer,       category: 'gravies', isSignature: true },
      { id: 'g19', name: 'Palak Paneer',             price: 199, tags: ['veg'],                 image: IMG.paneer,       category: 'gravies' },
      { id: 'g20', name: 'Kadai Paneer',             price: 199, tags: ['veg'],                 image: IMG.paneer,       category: 'gravies' },
      { id: 'g21', name: 'Mushroom Masala',          price: 199, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g22', name: 'Butter Mushroom',          price: 199, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g23', name: 'Aloo Gobi',                price: 180, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g24', name: 'Aloo Jeera (Dry)',         price: 149, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g25', name: 'Dal Tadka (Fry)',          price: 149, tags: ['veg'],                 image: IMG.soup,         category: 'gravies' },
      { id: 'g26', name: 'Babycorn Masala',          price: 199, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g27', name: 'Dal Fry',                  price: 149, tags: ['veg'],                 image: IMG.soup,         category: 'gravies' },
      { id: 'g28', name: 'Tomato Masala',            price: 149, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
      { id: 'g29', name: 'Mix Veg Curry',            price: 149, tags: ['veg'],                 image: IMG.vegStarter,   category: 'gravies' },
    ],
  },

  // ─────────────────────── SEA FOOD ────────────────────────────────────────
  {
    id: 'seafood',
    name: 'Sea Food',
    icon: '🦐',
    description: 'Fresh-from-the-sea catch prepared with coastal spice mastery',
    items: [
      { id: 'sf1',  name: 'Tawa Fish',          price: 299, tags: ['non-veg'],           image: IMG.seafood, category: 'seafood' },
      { id: 'sf2',  name: 'Fried Fish',         price: 299, tags: ['non-veg'],           image: IMG.seafood, category: 'seafood' },
      { id: 'sf3',  name: 'Fish Finger',        price: 299, tags: ['non-veg'],           image: IMG.seafood, category: 'seafood' },
      { id: 'sf4',  name: 'Fish Chilli',        price: 299, tags: ['non-veg', 'spicy'],  image: IMG.seafood, category: 'seafood' },
      { id: 'sf5',  name: 'Schezwan Fish',      price: 299, tags: ['non-veg', 'spicy'],  image: IMG.seafood, category: 'seafood' },
      { id: 'sf6',  name: 'Schezwan Prawns',    price: 299, tags: ['non-veg', 'spicy'],  image: IMG.seafood, category: 'seafood' },
      { id: 'sf7',  name: 'Prawns Manchurian',  price: 299, tags: ['non-veg'],           image: IMG.seafood, category: 'seafood' },
      { id: 'sf8',  name: 'Prawns Chettinadu', price: 299, tags: ['non-veg', 'spicy', 'signature'], image: IMG.seafood, category: 'seafood', isSignature: true },
      { id: 'sf9',  name: 'Fish Masala',        price: 299, tags: ['non-veg', 'spicy'],  image: IMG.seafood, category: 'seafood' },
      { id: 'sf10', name: 'Fish Pepper Masala', price: 299, tags: ['non-veg', 'spicy'],  image: IMG.seafood, category: 'seafood' },
      { id: 'sf11', name: 'Goan Fish Curry',    price: 299, tags: ['non-veg', 'signature'], image: IMG.seafood, category: 'seafood', isSignature: true },
      { id: 'sf12', name: 'Garlic Prawns',      price: 299, tags: ['non-veg'],           image: IMG.seafood, category: 'seafood' },
      { id: 'sf13', name: 'Prawns Do Pyaza',    price: 299, tags: ['non-veg'],           image: IMG.seafood, category: 'seafood' },
      { id: 'sf14', name: 'Prawns Masala',      price: 299, tags: ['non-veg', 'spicy'],  image: IMG.seafood, category: 'seafood' },
      { id: 'sf15', name: 'Fish Tikka Masala',  price: 299, tags: ['non-veg', 'signature'], image: IMG.seafood, category: 'seafood', isSignature: true },
      { id: 'sf16', name: 'Fish Manchurian',    price: 299, tags: ['non-veg'],           image: IMG.seafood, category: 'seafood' },
    ],
  },

  // ─────────────────────── CHINESE / FRIED RICE & NOODLES ─────────────────
  {
    id: 'chinese',
    name: 'Chinese — Fried Rice & Noodles',
    icon: '🥢',
    description: 'Indo-Chinese flavours elevated — wok-tossed to smoky perfection',
    items: [
      { id: 'c1',  name: 'Veg Fried Rice',              price: 99,  tags: ['veg'],           image: IMG.friedRice, category: 'chinese' },
      { id: 'c2',  name: 'Mixed Veg Fried Rice',        price: 129, tags: ['veg'],           image: IMG.friedRice, category: 'chinese' },
      { id: 'c3',  name: 'Veg Schezwan Fried Rice',     price: 129, tags: ['veg', 'spicy'],  image: IMG.friedRice, category: 'chinese' },
      { id: 'c4',  name: 'Mushroom Fried Rice',         price: 129, tags: ['veg'],           image: IMG.friedRice, category: 'chinese' },
      { id: 'c5',  name: 'Paneer Fried Rice',           price: 129, tags: ['veg'],           image: IMG.friedRice, category: 'chinese' },
      { id: 'c6',  name: 'Baby Corn Fried Rice',        price: 129, tags: ['veg'],           image: IMG.friedRice, category: 'chinese' },
      { id: 'c7',  name: 'Egg Fried Rice',              price: 120, tags: ['egg'],           image: IMG.friedRice, category: 'chinese' },
      { id: 'c8',  name: 'Chicken Fried Rice',          price: 149, tags: ['non-veg'],       image: IMG.friedRice, category: 'chinese' },
      { id: 'c9',  name: 'Chicken Schezwan Fried Rice', price: 149, tags: ['non-veg', 'spicy'], image: IMG.friedRice, category: 'chinese' },
      { id: 'c10', name: 'Non Veg Mixed Fried Rice',    price: 199, tags: ['non-veg'],       image: IMG.friedRice, category: 'chinese' },
      { id: 'c11', name: 'Prawns Fried Rice',           price: 199, tags: ['non-veg'],       image: IMG.friedRice, category: 'chinese' },
      { id: 'c12', name: 'Fish Fried Rice',             price: 199, tags: ['non-veg'],       image: IMG.friedRice, category: 'chinese' },
      { id: 'c13', name: 'Veg Noodles',                 price: 99,  tags: ['veg'],           image: IMG.noodles,   category: 'chinese' },
      { id: 'c14', name: 'Veg Schezwan Noodles',        price: 120, tags: ['veg', 'spicy'],  image: IMG.noodles,   category: 'chinese' },
      { id: 'c15', name: 'Mixed Veg Noodles',           price: 129, tags: ['veg'],           image: IMG.noodles,   category: 'chinese' },
      { id: 'c16', name: 'Mushroom Noodles',            price: 129, tags: ['veg'],           image: IMG.noodles,   category: 'chinese' },
      { id: 'c17', name: 'Paneer Fried Noodles',        price: 129, tags: ['veg'],           image: IMG.noodles,   category: 'chinese' },
      { id: 'c18', name: 'Baby Corn Noodles',           price: 129, tags: ['veg'],           image: IMG.noodles,   category: 'chinese' },
      { id: 'c19', name: 'Egg Noodles',                 price: 120, tags: ['egg'],           image: IMG.noodles,   category: 'chinese' },
      { id: 'c20', name: 'Egg Schezwan Noodles',        price: 129, tags: ['egg', 'spicy'],  image: IMG.noodles,   category: 'chinese' },
      { id: 'c21', name: 'Chicken Noodles',             price: 149, tags: ['non-veg'],       image: IMG.noodles,   category: 'chinese' },
      { id: 'c22', name: 'Chicken Schezwan Noodles',    price: 149, tags: ['non-veg', 'spicy'], image: IMG.noodles, category: 'chinese' },
      { id: 'c23', name: 'Prawns Noodles',              price: 199, tags: ['non-veg'],       image: IMG.noodles,   category: 'chinese' },
      { id: 'c24', name: 'Fish Noodles',                price: 199, tags: ['non-veg'],       image: IMG.noodles,   category: 'chinese' },
      { id: 'c25', name: 'Non Veg Mixed Noodles',       price: 199, tags: ['non-veg'],       image: IMG.noodles,   category: 'chinese' },
    ],
  },

  // ─────────────────────── RICE & BREADS ───────────────────────────────────
  {
    id: 'rice-breads',
    name: 'Rice & Breads',
    icon: '🫓',
    description: 'Fluffy naans, crispy rotis and fragrant rice to complement every dish',
    items: [
      { id: 'r1',  name: 'Curd Rice',           price: 120, tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r2',  name: 'Basmati Plain Rice',  price: 90,  tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r3',  name: 'Jeera / Ghee Rice',   price: 120, tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r4',  name: 'Kaju Rice',           price: 149, tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r5',  name: 'Biryani Rice',        price: 90,  tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r6',  name: 'Stem Rice',           price: 90,  tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r7',  name: 'Veg Pulao',           price: 150, tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r8',  name: 'Kaju Jeera Rice',     price: 170, tags: ['veg'], image: IMG.biryani, category: 'rice-breads', subCategory: 'Rice' },
      { id: 'r9',  name: 'Plain Naan',          price: 25,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r10', name: 'Butter Naan',         price: 30,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r11', name: 'Garlic Naan',         price: 40,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r12', name: 'Cheese Naan',         price: 50,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r13', name: 'Methi Kulcha',        price: 50,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r14', name: 'Tandoori Roti',       price: 20,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r15', name: 'Butter Roti',         price: 25,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r16', name: 'Lachha Paratha',      price: 50,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r17', name: 'Aloo Paratha',        price: 50,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r18', name: 'Pudina Paratha',      price: 35,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r19', name: 'Onion Kulcha',        price: 35,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r20', name: 'Masala Kulcha',       price: 50,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
      { id: 'r21', name: 'Butter Kulcha',       price: 40,  tags: ['veg'], image: IMG.naan, category: 'rice-breads', subCategory: 'Breads' },
    ],
  },

  // ─────────────────────── DESSERTS ────────────────────────────────────────
  {
    id: 'desserts',
    name: 'Desserts',
    icon: '🍮',
    description: 'A sweet finale — traditional Indian sweets and modern indulgences',
    items: [
      { id: 'd1', name: 'Ice Cream (Vanilla / Chocolate / Butter Scotch)', price: 60,  tags: ['veg'], image: IMG.dessert, category: 'desserts' },
      { id: 'd2', name: 'Carrot Halwa',                                    price: 90,  tags: ['veg', 'signature'], image: IMG.dessert, category: 'desserts', isSignature: true },
      { id: 'd3', name: 'Apricot Delight',                                 price: 99,  tags: ['veg', 'signature'], image: IMG.dessert, category: 'desserts', isSignature: true },
    ],
  },

  // ─────────────────────── BEVERAGES ───────────────────────────────────────
  {
    id: 'beverages',
    name: 'Beverages',
    icon: '🥤',
    description: 'Refreshing drinks to complement your meal — from chilled lassis to effervescent mocktails',
    items: [
      { id: 'bv1',  name: 'Thandali Lassi',            price: 50, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv2',  name: 'Sweet Lassi',               price: 60, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv3',  name: 'Salted Lassi',              price: 50, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv4',  name: 'Mango Lassi (Seasonal)',    price: 80, tags: ['veg', 'signature'], image: IMG.beverage, category: 'beverages', isSignature: true },
      { id: 'bv5',  name: 'Lime Juice',                price: 30, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv6',  name: 'Lima Soda',                 price: 40, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv7',  name: 'Mojito',                    price: 70, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv8',  name: 'Coke',                      price: 20, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv9',  name: 'Fanta',                     price: 20, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv10', name: 'Thums Up',                  price: 20, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv11', name: 'Maaza',                     price: 20, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv12', name: 'Soft Drink (250ml Bottle)', price: 25, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv13', name: 'Soft Drink (750ml Bottle)', price: 50, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
      { id: 'bv14', name: 'Water Bottle',              price: 20, tags: ['veg'],           image: IMG.beverage, category: 'beverages' },
    ],
  },
];

// Featured / Signature dishes for homepage
export const signatureDishes = [
  { id: 'm22', name: 'Tandoori Chicken Mandi 4PC', price: 1000, cuisine: 'Arabian Mandi', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=800&q=80', description: 'Tender whole chicken marinated in our secret spice blend, slow-smoked over charcoal' },
  { id: 'b1',  name: 'Hyderabadi Chicken Dum Biryani', price: 149, cuisine: 'Hyderabadi', image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=800&q=80', description: 'Aromatic saffron-laced basmati layered with tender chicken — a Nizami legacy' },
  { id: 'g1',  name: 'Butter Chicken', price: 249, cuisine: 'Mughlai', image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&q=80', description: 'Velvety tomato-cream sauce enrobing succulent chicken in classic Mughal style' },
  { id: 'nv47', name: 'SPL Tandoori Platter', price: 899, cuisine: 'Tandoori', image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&q=80', description: 'Six premium tandoori preparations — a celebration of fire, spice & artistry' },
  { id: 'm10', name: 'Chicken Al Faham (Full)', price: 1000, cuisine: 'Arabian', image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80', description: 'Whole chicken marinated in Middle-Eastern spices, charcoal-grilled to smoky perfection' },
  { id: 'b2',  name: 'Hyderabadi Mutton Dum Biryani', price: 249, cuisine: 'Hyderabadi', image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=800&q=80', description: 'Slow-cooked tender mutton in fragrant dum biryani, a culinary heirloom' },
];

export const restaurantInfo = {
  name: 'The Magic Spice',
  tagline: 'Multi Cuisine Restaurant',
  since: 2019,
  phone: '9849 122 963',
  whatsapp: '919849122963',
  email: 'info@themagicspice.in',
  timings: '11:00 AM – 11:00 PM',
  daysOpen: 'All Days',
  locations: [
    { city: 'Nagarkurnool', address: 'Nagarkurnool, Telangana', lat: 16.4954018, lng: 78.296533, isMain: true },
    { city: 'Wanaparthi', address: 'Wanaparthi, Telangana', lat: 16.3647, lng: 78.0601, isMain: false },
    { city: 'Bangalore', address: 'Bangalore, Karnataka', lat: 12.9716, lng: 77.5946, isMain: false },
  ],
  mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3808.936!2d78.2965!3d16.4954!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bca6bad653e0a3f%3A0x86a6b5829bb4d70e!2sTHE%20MAGIC%20SPICE!5e0!3m2!1sen!2sin!4v1234567890',
  googleMapsLink: 'https://www.google.com/maps/place/THE+MAGIC+SPICE/@16.4954018,78.296533,17z',
  catering: ['Birthday Parties', 'Corporate Events', 'Barbeque Parties', 'All Types of Functions'],
  socialLinks: {
    instagram: 'https://instagram.com/themagicspice',
    facebook: 'https://facebook.com/themagicspice',
    youtube: '',
    swiggy: '',
    zomato: '',
  },
};
